name: Java CI

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
    - name: Install libsqlite3-dev
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get -q install libsqlite3-dev
        apt-get --help
        #dpkg -L libsqlite3-dev
    - name: Install libsqlite3 dll
      if: matrix.os == 'windows-latest'
      run: choco install sqlite --params "/NoTools" --no-progress
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      if: matrix.os == 'ubuntu-latest'
      run: JAVA_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu/ mvn -q -B test --file pom.xml
    - name: Build with Maven
      if: matrix.os == 'windows-latest'
      shell: cmd
      run: |
        dir C:\ProgramData\chocolatey /s /b
        set JAVA_LIBRARY_PATH=C:\ProgramData\chocolatey\lib\SQLite\tools
        mvn -q -B test --file pom.xml
