name: Java CI

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
    - name: Install libsqlite3-dev
      if: matrix.os == 'ubuntu-latest'
      run: sudo apt-get -q install libsqlite3-dev
    - name: Install libsqlite3 dll
      if: matrix.os == 'windows-latest'
      shell: cmd
      run: |
        rem vcpkg install sqlite3:x64-windows
        pacman -S mingw-w64-x86_64-sqlite3

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - uses: actions/checkout@v1

    - name: Build with Maven
      if: matrix.os == 'ubuntu-latest'
      run: |
        export LD_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu
        JAVA_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu mvn -q -B test --file pom.xml
    - name: Build with Maven
      if: matrix.os == 'windows-latest'
      shell: cmd
      run: |
        rem et JAVA_LIBRARY_PATH=C:\vcpkg\installed\x64-windows\bin\
        rem set PATH=%PATH%;%JAVA_LIBRARY_PATH%
        mvn -q -B test --file pom.xml
